In [35]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score

In [43]:
df=pd.read_csv("HousePricePrediction.csv")
df1=df.copy()

In [37]:
df1.dtypes

Id                int64
MSSubClass        int64
MSZoning         object
LotArea           int64
LotConfig        object
BldgType         object
OverallCond       int64
YearBuilt         int64
YearRemodAdd      int64
Exterior1st      object
BsmtFinSF2      float64
TotalBsmtSF     float64
SalePrice       float64
dtype: object

In [38]:
df1.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [39]:
df1["MSZoning"]=df1["MSZoning"].fillna("not mentioned")
df1["Exterior1st"]=df1["Exterior1st"].fillna("not mentioned")

if df1["BsmtFinSF2"].skew()>1:
    df1["BsmtFinSF2"]=df1["BsmtFinSF2"].fillna(df1["BsmtFinSF2"].median())
elif df1["BsmtFinSF2"].skew()<-1:
    df1["BsmtFinSF2"]=df1["BsmtFinSF2"].fillna(df1["BsmtFinSF2"].mean())


if df1["TotalBsmtSF"].skew()>1:
    df1["TotalBsmtSF"]=df1["TotalBsmtSF"].fillna(df1["TotalBsmtSF"].median())
elif df1["TotalBsmtSF"].skew()<-1:
    df1["TotalBsmtSF"]=df1["TotalBsmtSF"].fillna(df1["TotalBsmtSF"].mean())



if df1["SalePrice"].skew()>1:
    df1["SalePrice"]=df1["SalePrice"].fillna(df1["SalePrice"].median())
elif df1["SalePrice"].skew()<-1:
    df1["SalePrice"]=df1["SalePrice"].fillna(df1["SalePrice"].mean())

In [40]:
df1.isnull().sum()

Id              0
MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [41]:

X=df1.drop(columns=["SalePrice"])
y=df1["SalePrice"]
cols=["MSZoning","LotConfig","BldgType","Exterior1st"]
X=pd.get_dummies(X,columns=cols,drop_first=True,dtype=int)

In [42]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=LinearRegression()

model.fit(x_train,y_train)

prediction=model.predict(x_test)

evaluation=r2_score(y_test,prediction)
print(evaluation)

0.3540291398345289